### ISSUE TITLE
Weird exit signal

### ISSUE THREAD

**Issue by croqaz** [atom/watcher#110]
Hi,

This library somehow blocks the `signal-exit` library from announcing the exit.
I even tried with alwaysLast option:

```js
const onExit = require('signal-exit')
onExit(function (code, signal) {
  console.log('process exited!')
}, { alwaysLast: true })
```

When I switch to another watching library, the exit is called normal.

**Comment by croqaz** [comment]
## Update:

It's actually the exact same thing with similar watching libraries (axosoft/nsfw, bevry/watchr).

The signal is actually being sent, I can see the console.log, but the next process in a PIPE doesn't see the message. I'm using the Node process with `| npx pino` and weird enough, it doesn't catch the final log message if I'm using any watcher other than chokidar.

It's really weird, but not so much of an issue, because the exit code is actually executed as it should.

This issue can be closed.

**Comment by smashwilson** [comment]
Huh, bizarre! Could it have to do with the additional threads that are spawned to do the watching, maybe? This library spawns one or two (a watcher and an optional poller), nsfw spawns two per watched root.

**Comment by smashwilson** [comment]
🤔 If it is the background threads, then #11 may help? You'd just need to be sure to `await watcher.stop()` or what have you before the process terminates.

**Comment by croqaz** [comment]
Hey, thank you for your answers.

I'm calling `stopWatchers` at exit and `dispose` on each watcher (I'm using 2), but the pipe still doesn't transmit the last messages. I tried with `tee` as well.

It works if I use direct > into a file though.
