### ISSUE TITLE
Any plan to publish binaries?

### ISSUE THREAD

**Issue by caseywebdev** [atom/watcher#134]
I don't have much experience publishing binaries for node bindings but I know it's a nice time saver on the package install side.

**Comment by smashwilson** [comment]
> I don't have much experience publishing binaries for node bindings

Neither do I, but setting this up as a prebuilt would be 👍 I don't _think_ there's that much to it?

I'm more actively working [elsewhere](https://github.com/atom/atom/pulls?utf8=%E2%9C%93&q=is%3Apr+label%3Aweekly-focus) these days, but I'd be happy to merge a PR that sets this up in the meantime if someone has bandwidth to get to it before I have a chance to :smile:
