### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by caseywebdev** [atom/watcher#141]
The latest release (`1.0.3` at time of writing) fails to build on Node.js 10, but `master` builds fine, likely because `nan` has been updated to latest in this repo since the last release. Publishing a new release would be greatly appreciated!

**Comment by smashwilson** [comment]
Noted 👍 

I do want to get #135 merged first so that we can try the prebuilt binary strategy. Let me have a look at that first 😄

**Comment by smashwilson** [comment]
Done. It took me a few tries to get `node-pre-gyp-github` to work properly.

We also only have prebuilt binaries for MacOS right now, because I cut the release on my Mac. I'll need to 🔧 the CI on AppVeyor and Travis to get it to publish binaries on tags, I suspect.
