### ISSUE TITLE
Yarn add hangs on Linux

### ISSUE THREAD

**Issue by nono** [atom/watcher#186]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

When running `yarn add @atom/watcher`, it hangs forever on linux.

### Steps to Reproduce

1. `npm install -g yarn`
2. `mkdir project && cd project && yarn init`
3. `yarn add @atom/watcher`

**Expected behavior:**

The package is installed in node_modules and the `package.json` is updated (`yarn.lock` too).

**Actual behavior:**

`yarn add @atom/watcher` hangs and `package.json` is not updated.

**Reproduces how often:**

100%

### Versions

@atom/watcher@1.2.0.

### Additional Information

Maybe it's related to #185

**Comment by nono** [comment]
I have those process in `ps aux`:

```
nono     13017 41.0  1.0 1241108 84464 pts/8   Sl+  14:26   0:00 node /home/nono/bin/yarn add @atom/watcher
nono     13027  0.0  0.0   4632   832 ?        Ss   14:26   0:00 /bin/sh -c prebuild-install || node-gyp rebuild
nono     13028 13.0  0.4 988000 36680 ?        Sl   14:26   0:00 node /home/nono/tmp/project/node_modules/@atom/watcher/node_modules/.bin/prebuild-install
```

**Comment by smashwilson** [comment]
> Maybe it's related to #185

Yeah, this is the same problem 😞 Closing this issue in favor of that one to keep things centralized ➡️
