### ISSUE TITLE
Creation events dropped 

### ISSUE THREAD

**Issue by smashwilson** [atom/watcher#35]
When a directory with existing contents is renamed into a watch root from the outside, the subdirectory structure within it is watched correctly, but no "created" events are generated for any of its contents. I can't just synthesize them myself because the entry could also have been added in the window of time between the creation of the watch descriptor and the `readdir()` call that reached that entry, in which case an `IN_CREATE` event will be reported normally through inotify, so we'd have generated a duplicate one. Similarly, if a subdirectory and its contents are created rapidly enough, the `IN_CREATE` events for its entries could be delivered before the watch descriptor is installed.

Essentially, there's a race condition between the `inotify_add_watch()` call and the `readdir()` scan that can cause creation events for subdirectories to be dropped.

@damieng how important is this to atom-ide? Will the language server be confused if create messages are dropped when directories are moved around, or will the directory creation message and modifications or deletions be sufficient? (I'm deciding if I should tackle this for the initial release or not, because it's fairly hairy.)

**Comment by damieng** [comment]
I'm not sure I fully understand what this is. Can you provide a sequence?  Does this behavior differ from nsfw etc?

**Comment by smashwilson** [comment]
> Can you provide a sequence?

Right, that would be a lot clearer :smile:

1. Begin with the following directory tree:

```
outside/
  dir/
    file0.txt
    file1.txt
    subdir/
      file2.txt
watchroot/
```

2. Create a recursive watcher on `watchroot/` and wait for it to begin.
3. Move `dir/` into `watchroot/`.

```sh
$ mv /outside/dir /watchroot/
```

```
outside/
watchroot/
  dir/
    file0.txt
    file1.txt
    subdir/
      file2.txt
```

I'd expect these events to be generated:

```js
[
  { action: 'created', kind: 'directory', path: '/watchroot/dir/' },
  { action: 'created', kind: 'file', path: '/watchroot/dir/file0.txt' },
  { action: 'created', kind: 'file', path: '/watchroot/dir/file1.txt' },
  { action: 'created', kind: 'directory', path: '/watchroot/dir/subdir' },
  { action: 'created', kind: 'file', path: '/watchroot/dir/subdir/file2.txt' }
]
```

But right now only one is:

```js
[
  { action: 'created', kind: 'directory', path: '/watchroot/dir/' }
]
```

> Does this behavior differ from nsfw etc?

I just checked and nsfw also emits only the directory creation event on MacOS. So we aren't inconsistent, at least.

**Comment by damieng** [comment]
VSCode are also using nsfw on the mac so if this was an issue with LSP integration it's probably quite well known.  I think we're okay.

**Comment by smashwilson** [comment]
:+1: Okay, great. They must automatically index recursively beneath newly created directories, then. Closing this out then 🙇
