### ISSUE TITLE
Fall back to polling

### ISSUE THREAD

**Issue by smashwilson** [atom/watcher#5]
Fall back to a polling mechanism in a polling thread if normal filesystem watching mechanisms fail, or if explicitly requested for a specific watcher.

**Comment by Alhadis** [comment]
Doesn't Node [already have a facility for this](https://nodejs.org/api/fs.html#fs_availability)?

**Comment by smashwilson** [comment]
Yes, it does, and it's one possibility for an implementation.

Polling mode will mostly likely be triggered if you (a) open a project on a remotely-mounted filesystem or (b) run out of inotify handles on Linux. My goal would be for polling mode to fail by increasing event latency rather than eating your CPU if you open a large project (~10k files, say). I'm guessing that `fs.watchFile` would err on the "eat your CPU" side :smile:
